# See other possible options with:
# python main.py fit --print_config

model:
  model_name: resnet50
  weights: DEFAULT
  num_classes: 13
  label_names:
    - bhaji
    - chapati
    - githeri
    - kachumbari
    - kukuchoma
    - mandazi
    - masalachips
    - matoke
    - mukimo
    - nyamachoma
    - pilau
    - sukumawiki
    - ugali
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 0.0
  scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
      T_max: 100

trainer:
  max_epochs: 1
  precision: 16-mixed
  fast_dev_run: false
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: ${model.model_name}
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: valid/loss
        min_delta: 0.001
        patience: 10
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: valid/f1_macro
        mode: max
        filename: ${model.model_name}-epoch-{epoch:02d}
        auto_insert_metric_name: false
        save_weights_only: true

data:
  root_folder: /workspace/opencv-pytorch-classification-project-2-resize
  batch_size: 256
  prefetch_factor: 4
  num_workers: 0
  target_size: 256
  train_split: 0.75
  train_augmentations:
    - name: HorizontalFlip
    - name: ColorJitter
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.05
      p: 0.5
    - name: GaussianBlur
      blur_limit: [3, 7]
      p: 0.2
    - name: GaussNoise
      p: 0.2
    - name: Sharpen
      alpha: [0.2, 0.5]
      lightness: [0.5, 1.0]
      p: 0.3
    - name: Affine
      translate_percent: 0.1
      rotate: [-20, 20]
      border_mode: 0  # cv2.BORDER_CONSTANT
      fill: 0
      p: 0.5
    - name: CoarseDropout
      num_holes_range: [1, 8]
      hole_height_range: [16, 32]
      hole_width_range: [16, 32]
      p: 0.3
    - name: Normalize
    - name: ToTensorV2
  eval_augmentations:
    - name: Normalize
    - name: ToTensorV2
ckpt_path: null
weights_only: null
seed_everything: 21
