n_trials: 30
max_epochs: 10
logger_name: optuna
pruner:
  n_startup_trials: 3
  n_warmup_steps: 5
search_space:
  lr:
    type: float
    low: 1.0e-6
    high: 1.0e-2
    log: true
  weight_decay:
    type: float
    low: 1.0e-6
    high: 1.0e-2
    log: true
  batch_size:
    type: int
    low: 32
    high: 384
    log: False
  model_name:
    type: categorical
    choices:
      - resnet18
      - resnet34
      - resnet50
      - convnext_tiny
      - convnext_small
      - efficientnet_b0
      - mobilenet_v3_large
      - mobilenet_v3_small
      - shufflenet_v2_x1_0
      - regnet_y_400mf
      - regnet_y_800mf
      - mnasnet1_3
